module.exports = {
  balloon0: 'assets/balloon_512w.png',
  balloon1: 'assets/balloon_1.svg',
  balloon2: 'assets/balloon_2.svg',
  balloon3: 'assets/balloon_3.svg',
  bg: 'assets/bg.png',
  shop: 'assets/carnival_shop.png',
  carousel: 'assets/carousel.png',
  dart: 'assets/dart.png',
  loader_bg: 'assets/loader_bg.png',
  logo: 'assets/logo.png',
  mrQBody: 'assets/mrQ_body.png',
  mrQHat: 'assets/mrQ_hat.png',
  mrQLeftArm: 'assets/mrQ_left_arm.png',
  mrQRightArm: 'assets/mrQ_right_arm.png',
  mrQ: 'assets/mrQ.png',
  reward: 'assets/reward.png',
  target: 'assets/target.png',
};
